---
  - name: prometheus package
    apt:
      name: prometheus

  - name: prometheus config
    template:
      src: prometheus.yaml.j2
      dest: /etc/prometheus/prometheus.yml
    notify:
      - Restart prometheus

  - name: Adjust prometheus reachability
    lineinfile:
      path: /etc/default/prometheus
      regexp: '^ARGS='
      line: ARGS='--web.external-url=http://{{ ansible_host }}/prometheus'
    notify:
      - Restart prometheus
